apiVersion: v1
kind: Secret
metadata:
  name: agro-secrets
  namespace: agro-iot
type: Opaque
stringData:
    Jwt__Key: "DeelopmentIUzaP66%+W|yX0=3*"
    Jwt__Issuer: "Users.API"
    Jwt__Audience: "Users.API.Client"
    ConnectionStrings__DbConnection: "Server=sqlserver,1434;Database=Users;User Id=sa;Password=password@1;TrustServerCertificate=True;Encrypt=False;"
    ConnectionStrings__RabbitMQ: "amqp://guest:guest@rabbitmq:5672"
    RabbitMQ__Host: "rabbitmq"
    RabbitMQ__User: "guest"
    RabbitMQ__Password: "guest"
    SA_PASSWORD: "password@1"